export const npcDialogs: any = {
	ariadne: [
		"I saw you approach the Nexus. I hoped you might. Thank you, Like-Traveller. This mission has significance to all like us.",
		"The Quicksilver Synthesis Companion is a skilled artisan. Have you seen its crafted faces, Like-Traveller? Indistinguishable from genuine flesh.",
		"The nature of these of disturbances worries me, Like-Traveller. I do not often venture from the Anomaly, but what I encountered out there was more than a likeness.",
		"These disturbances are a window looking back at this universe, Like-Traveller. In light or in darkness, both sides of the pane are valid. I am at peace with it. We both are.",
		"I saw you approach the Nexus. I hoped you might. Thank you, Like-Traveller. This mission has significance to all like us.",
		"How long now have we danced to this rhythm? The regularity of these disturbances brings a sort of comfort.",
		"There is still cause for hope, Like-Traveller, even in the face of calamity. I have a plan...",
		"I'm home. I am finally home. Like-Traveller, I am so glad to look upon your face.",
		"Ah, Like-Traveller. You have returned.",
		"Their face twists into something half-resembling a smile."
	],
	gemini: [
		"You're investigating the disturbance, my friend? I hope you're taking companions.",
		"Gemini gives me a watery smile, but seems distracted. They glance repeatedly over at Hesperus.",
		"Are you well, my friend? I apologise if I seem discouraging. Of course I am grateful for the efforts of Travellers like yourself. And Hesperus. If it weren't for their adventurous nature, we would never have met.",
		"I saw the disturbance with my own eyes, my friend. I felt alive out there. I remembered how much I miss adventure.",
		"You're investigating the disturbance, my friend? I hope you're taking companions.",
		"Hello! Ah, it brings me such joy to greet you. The danger of these disturbances aside, I am glad to be part of this effort at your side.",
		"Ariadne has disappeared!",
		"I tried to stop them -- I tried to make them see reason! Oh, I hope they are safe...",
		"Ariadne has returned! Our friend is safe! Ah, rejoice!",
		"Gemini looks at schematics for Exosuits. They don’t seem to notice my approach..."
	],
	mercury: [
		"This will be a test of fortitude, Portal-Adept.",
		"The solemn Traveller assesses me. Their eyes linger over my face, as though inspecting it for injury.",
		"I am pleased to see you alive. Will this be your first encounter with one of these disturbances?",
		"These disturbances fill me with a great unease.",
		"Our work is of great importance to this universe. Take pride in your contribution, Portal-Adept.",
		"This will be a test of fortitude, Portal-Adept.",
		"Mercury regards me silently. There is an intensity in their pale eyes that I can't quite identify. Is it hunger? Resentment? Envy?",
		"I often wonder about the nature of our existence, Portal-Adept. What Ariadne's recent disappearance means for us.",
		"There are some who believe the Travellers to be the same soul, split across countless iterations and universes.",
		"How we might have been, had we lived different lives...",
		"Calamity has befallen us, Portal-Adept. A thousand Korvax souls have been severed from the Convergence.",
		"The result of a fellow Traveller's ambition exceeding their grasp. Hesperus was working with the Korvax to try to simulate the Abyss itself. It came for them instead.",
		"If Hesperus returns to us, do you believe we can still trust them? They have much to answer for.",
		"These are grim times, Portal-Adept. Our community has fallen to strife."
	],
	tethys: [
		"Ah. So you've signed up to investigate this 'disturbance' Nada's been so worked up about.",
		"Off to investigate this latest disturbance? Better you than me. Though it might be nice to get out of here. The others won't shut up about it.",
		"Tethys seems more still, less fidgety than usual. They regard me quietly.",
		"These disturbances are... something's really wrong. I went and saw for myself. Even my exosuit seemed to panic when I got close.",
		"It feels so good to step out of hiding from time to time. It's worth it.",
		"Ah. So you've signed up to investigate this 'disturbance' Nada's been so worked up about.",
		"Tethys lets out a bad-tempered sigh. They say nothing, impatient to get this conversation over with.",
		"I once lived with a Vy'keen appearance mod for an entire year, you know? Did a lot of things I regret.",
		"I don't even know why I'm talking about it. We're not friends. You're a stranger.",
		"Tethys seems uneasy. Their lidless eyes flick towards Mercury's empty post.",
		"Tell me. Do you ever feel lonely?",
		"Traveller... has your Exosuit been operating at proper capacity?"
	],
	hesperus: [
		"I understand you have undertaken an investigation, kindred. Nada is fortunate to have your assistance.",
		"Have you discovered much about the disturbances, kindred? Please. Tell me of your experiences.",
		"The static spoke to me, kindred. It was a judgement I have endured before. This is a recurring nightmare.",
		"I do appreciate our impossible meetings, kindred. It is important to appreciate our peers.",
		"I understand you have undertaken an investigation, kindred. Nada is fortunate to have your assistance.",
		"Greetings. You are assisting with the disturbance? Many kindred are, today. I have had many conversations such as this. I find I never tire of them.",
		"Before you go, will you tell me a little about your most recent encounter with another kindred? A story to bookmark this conversation in my memory?",
		"Hesperus seems troubled. When I approach, they hide their data pad.None",
		"Ariadne has sent word... they are returning to us, kindred. They are safe.",
		"Ah, kindred... do not fear. All my guilt has been purged from my mind. Nanite Clusters can transform neurons with ease...",
		"The others will be back soon, kindred. We do not have much time..."
	],
}
